import { useState } from 'react';
import { NavLink, useNavigate } from 'react-router-dom';
import { useFilters } from '../contexts/FilterContext';
import { useAuth } from '../contexts/AuthContext';
import { usePrompts } from '../contexts/PromptContext';
import { getFilteredKpis, getFilteredDecisions } from '../data/siboniSelectors';

const BASE_NAV = [
  { path:'/app/home',      label:'Home',         icon:'M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6' },
  { path:'/app/board',     label:'Board Brief',  icon:'M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z' },
  { path:'/app/insights',  label:'Insights Hub', icon:'M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z' },
  { path:'/app/decisions', label:'Decision Hub', icon:'M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01' },
  { path:'/app/execution', label:'Execution Hub',icon:'M13 10V3L4 14h7v7l9-11h-7z' },
];

const FILTER_DEFS = [
  { key:'timeRange',   label:'Time range',  opts:['Last 30','Last 60','Last 90','Last 180','YTD'] },
  { key:'site',        label:'Plant',       opts:['Plano, Texas','Detroit','Pune','Michigan','All'] },
  { key:'country',     label:'Region',      opts:['USA','UK','India','Global'] },
  { key:'segment',     label:'Cust. Segment',opts:['OEM','Tier-1','Tier-2','All'] },
  { key:'productLine', label:'Prod. Line',  opts:['Car Axle','Braking Systems','Steering','EV Drivetrain','All'] },
];

export default function SiBoNiLayout({ children }) {
  const { filters, updateFilter, reset, snap, snapData, snapVisible, dismissSnap } = useFilters();
  const { user, logout } = useAuth();
  const { unviewedCount } = usePrompts();
  const navigate = useNavigate();
  const [collapsed, setCollapsed] = useState(false);
  const [snapEmail, setSnapEmail] = useState('');
  const [snapSent, setSnapSent] = useState(false);

  // Build role-based navigation
  const NAV = [
    ...BASE_NAV,
    ...(user?.role === 'analyst' ? [
      { path:'/app/analyst-studio', label:'Analyst Studio', icon:'M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z', highlight:true },
    ] : []),
    ...(user?.role === 'admin' ? [
      { path:'/app/analyst-studio', label:'Analyst Studio', icon:'M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z' },
      { path:'/app/admin', label:'Admin Panel', icon:'M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z M15 12a3 3 0 11-6 0 3 3 0 016 0z', adminOnly:true },
    ] : []),
  ];

  // Compute snap data lazily when modal is open
  const snapKpis     = snapVisible ? getFilteredKpis(filters).slice(0, 4) : [];
  const snapDecisions = snapVisible ? getFilteredDecisions(filters).slice(0, 2) : [];
  // KPI strip — always visible at bottom of every page
  const kpiStrip = getFilteredKpis(filters).slice(0, 6);

  const handleLogout = () => { logout(); navigate('/login'); };

  const handleDownload = () => {
    const ts = new Date().toLocaleString();
    const scopeStr = Object.entries(filters).map(([k,v]) => `${k}: ${v}`).join(' | ');
    const kpiLines = snapKpis.map(k => `  ${k.label.padEnd(36)} ${k.value.padStart(10)}  ${k.delta}  (${k.trend === 'up' ? '▲' : '▼'}) ${k.sublabel || ''}`);
    const decLines = snapDecisions.map(d =>
      `  [${d.ref}] ${d.title}\n    Why now: ${d.why_now}\n    Value at stake: ${d.value_at_stake}  |  Confidence: ${d.confidence}`);
    const lines = [
      '═══════════════════════════════════════════════════════════',
      '  EXECUTIVE SNAPSHOT — Gaksh Industrial Systems (GIS)',
      `  Generated: ${ts}`,
      `  Scope: ${scopeStr}`,
      '═══════════════════════════════════════════════════════════',
      '',
      '── KEY PERFORMANCE INDICATORS ──────────────────────────────',
      ...kpiLines,
      '',
      '── OPEN DECISIONS ──────────────────────────────────────────',
      ...decLines,
      '',
      '── GENERATED BY SiBoNi CXO Cockpit ────────────────────────',
      '  Confidential — for executive use only',
    ].join('\n');
    const blob = new Blob([lines], { type:'text/plain;charset=utf-8' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href = url;
    a.download = `GIS-Snapshot-${new Date().toISOString().slice(0,10)}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div style={{ display:'flex', height:'100vh', overflow:'hidden', background:'#f4f6f9' }}>

      {/* ── Sidebar ───────────────────────────────────────────────── */}
      <aside style={{
        width: collapsed ? 56 : 224,
        flexShrink:0,
        background:'#ffffff',
        borderRight:'1px solid #e2e8f0',
        display:'flex',
        flexDirection:'column',
        transition:'width .2s ease',
        overflow:'hidden',
        boxShadow:'1px 0 4px rgba(0,0,0,0.04)',
        zIndex:20,
      }}>

        {/* Logo row */}
        <div style={{ display:'flex', alignItems:'center', justifyContent: collapsed ? 'center' : 'space-between',
          padding: collapsed ? '14px 0' : '14px 16px',
          borderBottom:'1px solid #f1f5f9', flexShrink:0 }}>
          {!collapsed && (
            <div style={{ display:'flex', flexDirection:'column', lineHeight:1 }}>
              <span style={{ fontSize:18, fontWeight:900, color:'#0f172a', letterSpacing:2 }}>SiBoNi</span>
              <span style={{ fontSize:9, fontWeight:600, color:'#64748b', letterSpacing:1, marginTop:1 }}>CXO COCKPIT</span>
            </div>
          )}
          <button onClick={() => setCollapsed(v => !v)}
            style={{ background:'none', border:'1px solid #e2e8f0', borderRadius:6,
              cursor:'pointer', padding:'4px 6px', color:'#64748b', flexShrink:0 }}>
            <svg width={14} height={14} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
              {collapsed
                ? <path strokeLinecap="round" strokeLinejoin="round" d="M9 5l7 7-7 7"/>
                : <path strokeLinecap="round" strokeLinejoin="round" d="M15 19l-7-7 7-7"/>}
            </svg>
          </button>
        </div>



        {/* Navigation */}
        <nav style={{ padding: collapsed ? '8px 0' : '8px 0', flexShrink:0 }}>
          {NAV.map(item => (
            <NavLink key={item.path} to={item.path}
              style={({ isActive }) => ({
                display:'flex', alignItems:'center', gap:10,
                padding: collapsed ? '10px 0' : '9px 14px',
                justifyContent: collapsed ? 'center' : 'flex-start',
                textDecoration:'none',
                color: isActive ? '#2563eb' : item.highlight ? '#7c3aed' : item.adminOnly ? '#dc2626' : '#475569',
                background: isActive ? '#eff6ff' : item.highlight && !isActive ? '#faf5ff' : item.adminOnly && !isActive ? '#fef2f2' : 'transparent',
                borderLeft: isActive ? '3px solid #2563eb' : item.highlight ? '3px solid #7c3aed40' : item.adminOnly ? '3px solid #dc262640' : '3px solid transparent',
                fontWeight: isActive ? 700 : item.highlight || item.adminOnly ? 600 : 500,
                fontSize: 13,
                transition:'all .12s',
              })}>
              <svg width={16} height={16} viewBox="0 0 24 24" fill="none"
                stroke="currentColor" strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round">
                <path d={item.icon}/>
              </svg>
              {!collapsed && (
                <span style={{ whiteSpace:'nowrap', flex:1 }}>{item.label}</span>
              )}
              {/* Badge: unviewed analyst insights on Insights Hub (executive only) */}
              {!collapsed && item.path === '/app/insights' && user?.role === 'executive' && unviewedCount > 0 && (
                <span style={{ fontSize:10, fontWeight:800, background:'#f59e0b', color:'#ffffff',
                  borderRadius:99, padding:'1px 6px', minWidth:18, textAlign:'center' }}>
                  {unviewedCount}
                </span>
              )}
              {/* Badge: new label for Analyst Studio */}
              {!collapsed && item.highlight && (
                <span style={{ fontSize:9, fontWeight:800, background:'#7c3aed', color:'#ffffff',
                  borderRadius:99, padding:'1px 6px' }}>NEW</span>
              )}
            </NavLink>
          ))}
        </nav>

        {/* Filters section */}
        {!collapsed && (
          <div style={{ flex:1, overflowY:'auto', padding:'0 14px 14px',
            borderTop:'1px solid #f1f5f9', marginTop:4 }}>
            <div style={{ fontSize:10, fontWeight:700, color:'#94a3b8', letterSpacing:1,
              textTransform:'uppercase', padding:'10px 0 6px' }}>
              Filters
            </div>
            {FILTER_DEFS.map(fd => (
              <div key={fd.key} style={{ marginBottom:10 }}>
                <label style={{ display:'block', fontSize:10, fontWeight:600,
                  color:'#64748b', marginBottom:3 }}>{fd.label}</label>
                <select
                  value={filters[fd.key] || ''}
                  onChange={e => updateFilter(fd.key, e.target.value)}
                  style={{ width:'100%', fontSize:12, fontWeight:500, color:'#0f172a',
                    background:'#f8fafc', border:'1px solid #e2e8f0', borderRadius:7,
                    padding:'5px 8px', cursor:'pointer', appearance:'auto' }}>
                  {fd.opts.map(o => (
                    <option key={o} value={o}>{o}</option>
                  ))}
                </select>
              </div>
            ))}
          </div>
        )}

        {/* User row */}
        <div style={{ borderTop:'1px solid #f1f5f9', padding: collapsed ? '10px 0' : '10px 14px',
          display:'flex', alignItems:'center', gap:8, flexShrink:0,
          justifyContent: collapsed ? 'center' : 'flex-start' }}>
          <div style={{ width:28, height:28, borderRadius:'50%', background:'#eff6ff',
            display:'flex', alignItems:'center', justifyContent:'center', flexShrink:0 }}>
            <span style={{ fontSize:11, fontWeight:700, color:'#2563eb' }}>
              {user?.name?.charAt(0) || 'U'}
            </span>
          </div>
          {!collapsed && (
            <>
              <div style={{ flex:1, minWidth:0 }}>
                <div style={{ fontSize:12, fontWeight:700, color:'#0f172a',
                  whiteSpace:'nowrap', overflow:'hidden', textOverflow:'ellipsis' }}>
                  {user?.name || 'User'}
                </div>
                <div style={{ fontSize:10, color:'#94a3b8' }}>{user?.role || ''}</div>
              </div>
              <button onClick={handleLogout}
                style={{ background:'none', border:'none', cursor:'pointer',
                  color:'#94a3b8', padding:4, borderRadius:4 }}
                title="Sign out">
                <svg width={14} height={14} viewBox="0 0 24 24" fill="none"
                  stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
                  <path d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"/>
                </svg>
              </button>
            </>
          )}
        </div>
      </aside>

      {/* ── SNAP Report Modal ─────────────────────────────────────── */}
      {snapVisible && (
        <div style={{
          position:'fixed', inset:0, background:'rgba(15,23,42,0.70)',
          display:'flex', alignItems:'center', justifyContent:'center',
          zIndex:9999, padding:24,
        }}>
          <div style={{
            background:'#ffffff', borderRadius:16, width:'100%', maxWidth:660,
            maxHeight:'90vh', overflow:'auto',
            boxShadow:'0 20px 60px rgba(0,0,0,0.3)',
          }}>
            {/* Modal header */}
            <div style={{ background:'linear-gradient(135deg,#0f172a,#1e3a5f)', padding:'20px 24px', borderRadius:'16px 16px 0 0' }}>
              <div style={{ display:'flex', alignItems:'flex-start', justifyContent:'space-between' }}>
                <div>
                  <div style={{ fontSize:10, fontWeight:700, color:'#64748b', letterSpacing:1.5, textTransform:'uppercase', marginBottom:4 }}>Executive Snapshot</div>
                  <div style={{ fontSize:20, fontWeight:900, color:'#ffffff' }}>Gaksh Industrial Systems</div>
                  <div style={{ fontSize:11, color:'#94a3b8', marginTop:4 }}>
                    {snapData?.label} · {snapData ? new Date(snapData.timestamp).toLocaleString('en-US',{dateStyle:'medium',timeStyle:'short'}) : ''}
                  </div>
                </div>
                <button onClick={() => { dismissSnap(); setSnapSent(false); setSnapEmail(''); }}
                  style={{ background:'rgba(255,255,255,0.1)', border:'none', borderRadius:8,
                    cursor:'pointer', padding:8, color:'#94a3b8', marginTop:2 }}>
                  <svg width={16} height={16} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12"/>
                  </svg>
                </button>
              </div>
            </div>

            {/* Modal body */}
            <div style={{ padding:'20px 24px', display:'flex', flexDirection:'column', gap:16 }}>

              {/* Filter context chips */}
              <div style={{ display:'flex', gap:6, flexWrap:'wrap' }}>
                {Object.entries(snapData?.filters || {}).map(([k, v]) => (
                  <span key={k} style={{ fontSize:11, fontWeight:600, background:'#f1f5f9', color:'#475569',
                    border:'1px solid #e2e8f0', padding:'3px 10px', borderRadius:99 }}>
                    {k}: <b>{v}</b>
                  </span>
                ))}
              </div>

              {/* KPI metrics grid */}
              <div>
                <div style={{ fontSize:11, fontWeight:700, color:'#94a3b8', textTransform:'uppercase',
                  letterSpacing:1, marginBottom:10 }}>Key Metrics</div>
                <div style={{ display:'grid', gridTemplateColumns:'repeat(2, 1fr)', gap:10 }}>
                  {snapKpis.map(k => (
                    <div key={k.id} style={{ background:'#f8fafc', border:'1px solid #e2e8f0', borderRadius:10, padding:'10px 14px' }}>
                      <div style={{ fontSize:10, fontWeight:600, color:'#94a3b8', marginBottom:4 }}>{k.label}</div>
                      <div style={{ display:'flex', alignItems:'baseline', gap:8 }}>
                        <span style={{ fontSize:22, fontWeight:900, color:'#0f172a' }}>{k.value}</span>
                        <span style={{ fontSize:11, fontWeight:700, color: k.trend==='up'?'#16a34a':'#dc2626' }}>{k.delta}</span>
                      </div>
                      <div style={{ fontSize:10, color:'#94a3b8', marginTop:2 }}>{k.sublabel}</div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Top decisions */}
              <div>
                <div style={{ fontSize:11, fontWeight:700, color:'#94a3b8', textTransform:'uppercase',
                  letterSpacing:1, marginBottom:10 }}>Open Decisions</div>
                <div style={{ display:'flex', flexDirection:'column', gap:8 }}>
                  {snapDecisions.map(d => (
                    <div key={d.id} style={{ background:'#f8fafc', border:'1px solid #e2e8f0', borderRadius:10, padding:'10px 14px' }}>
                      <div style={{ display:'flex', alignItems:'center', gap:8, marginBottom:4 }}>
                        <span style={{ fontSize:10, fontWeight:700, color:'#94a3b8' }}>{d.ref}</span>
                        <span style={{ fontSize:10, fontWeight:700, background:'#fef9c3', color:'#ca8a04',
                          border:'1px solid #fde68a', padding:'1px 7px', borderRadius:99 }}>{d.category}</span>
                        <span style={{ marginLeft:'auto', fontSize:11, fontWeight:700, color:'#dc2626' }}>{d.value_at_stake}</span>
                      </div>
                      <div style={{ fontSize:12, fontWeight:700, color:'#0f172a', marginBottom:3 }}>{d.title}</div>
                      <div style={{ fontSize:11, color:'#64748b', lineHeight:1.5 }}>{d.why_now?.substring(0, 120)}…</div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Email send */}
              {!snapSent ? (
                <div style={{ background:'#f0f9ff', border:'1px solid #bae6fd', borderRadius:10, padding:'14px 16px' }}>
                  <div style={{ fontSize:12, fontWeight:700, color:'#0369a1', marginBottom:10 }}>📧 Send as Board Report</div>
                  <div style={{ display:'flex', gap:8, marginBottom:8 }}>
                    <input value={snapEmail} onChange={e => setSnapEmail(e.target.value)}
                      placeholder="recipient@gis.com"
                      style={{ flex:1, fontSize:12, padding:'8px 12px', borderRadius:8,
                        border:'1px solid #bae6fd', outline:'none', background:'#ffffff' }}/>
                    <button onClick={() => { if(snapEmail.includes('@')) setSnapSent(true); }}
                      style={{ fontSize:12, fontWeight:700, padding:'8px 18px', borderRadius:8,
                        background: snapEmail.includes('@') ? '#2563eb' : '#94a3b8',
                        color:'#ffffff', border:'none', cursor: snapEmail.includes('@') ? 'pointer' : 'default' }}>
                      Send
                    </button>
                  </div>
                  <div style={{ fontSize:10, color:'#64748b' }}>
                    Includes: KPIs, decisions, signals and action plan for the selected filter scope.
                  </div>
                </div>
              ) : (
                <div style={{ background:'#f0fdf4', border:'1px solid #bbf7d0', borderRadius:10,
                  padding:'14px 16px', display:'flex', alignItems:'center', gap:10 }}>
                  <svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#16a34a" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7"/>
                  </svg>
                  <div>
                    <div style={{ fontSize:12, fontWeight:700, color:'#15803d' }}>Report sent successfully!</div>
                    <div style={{ fontSize:11, color:'#64748b' }}>Executive snapshot delivered to {snapEmail}</div>
                  </div>
                </div>
              )}

              {/* Download button */}
              <div style={{ display:'flex', gap:8 }}>
                <button onClick={dismissSnap}
                  style={{ flex:1, fontSize:12, fontWeight:700, padding:'10px 0', borderRadius:10,
                    background:'#f8fafc', border:'1px solid #e2e8f0', color:'#475569', cursor:'pointer' }}>
                  Close
                </button>
                <button onClick={handleDownload}
                  style={{ flex:1, fontSize:12, fontWeight:700, padding:'10px 0', borderRadius:10,
                    background:'linear-gradient(135deg,#2563eb,#4f46e5)', color:'#ffffff', border:'none', cursor:'pointer' }}>
                  ⬇ Download Snapshot
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* ── Main content ──────────────────────────────────────────── */}
      <main style={{ flex:1, overflow:'auto', display:'flex', flexDirection:'column' }}>

        {/* Top bar */}
        <div style={{ background:'#ffffff', borderBottom:'1px solid #e2e8f0',
          padding:'0 24px', height:52, display:'flex', alignItems:'center',
          justifyContent:'space-between', flexShrink:0,
          boxShadow:'0 1px 3px rgba(0,0,0,0.04)' }}>
          <div>
            <span style={{ fontSize:14, fontWeight:700, color:'#0f172a' }}>
              Gaksh Industrial Systems
            </span>
            <span style={{ fontSize:12, color:'#94a3b8', marginLeft:8 }}>
              {filters.timeRange} &bull; {filters.site} &bull; {filters.country}
            </span>
          </div>
          <div style={{ display:'flex', alignItems:'center', gap:8 }}>
            <button onClick={reset}
              style={{ fontSize:11, fontWeight:700, padding:'5px 12px',
                background:'#f8fafc', color:'#475569', border:'1px solid #e2e8f0',
                borderRadius:7, cursor:'pointer', letterSpacing:0.2 }}>
              ↺ Reset
            </button>
            <button onClick={snap}
              style={{ fontSize:11, fontWeight:700, padding:'5px 12px',
                background:'#eff6ff', color:'#2563eb', border:'1px solid #bfdbfe',
                borderRadius:7, cursor:'pointer', letterSpacing:0.2 }}>
              ⧉ Snap
            </button>
            <span style={{ fontSize:11, fontWeight:600, background:'#f0fdf4', color:'#16a34a',
              border:'1px solid #bbf7d0', padding:'3px 10px', borderRadius:99,
              display:'flex', alignItems:'center', gap:5 }}>
              <span style={{ width:6, height:6, borderRadius:'50%', background:'#16a34a',
                display:'inline-block' }} />
              Live
            </span>
          </div>
        </div>

        {/* Page content */}
        <div style={{ flex:1, overflow:'auto' }}>
          {children}
        </div>

        {/* ── Horizontal KPI Strip (bottom, persistent) ───────────── */}
        <div style={{
          background: '#ffffff',
          borderTop: '2px solid #e2e8f0',
          display: 'flex',
          alignItems: 'stretch',
          flexShrink: 0,
          height: 70,
          overflowX: 'auto',
          boxShadow: '0 -1px 4px rgba(0,0,0,0.04)',
        }}>
          {kpiStrip.map((k, i) => (
            <div key={k.id} style={{
              flex: '1 0 0',
              minWidth: 130,
              display: 'flex',
              flexDirection: 'column',
              justifyContent: 'center',
              padding: '0 18px',
              borderRight: i < kpiStrip.length - 1 ? '1px solid #f1f5f9' : 'none',
            }}>
              <div style={{ fontSize: 9, fontWeight: 700, color: '#94a3b8', marginBottom: 2,
                whiteSpace: 'nowrap', textTransform: 'uppercase', letterSpacing: 0.5 }}>
                {k.label}
              </div>
              <div style={{ display: 'flex', alignItems: 'baseline', gap: 5 }}>
                <span style={{ fontSize: 16, fontWeight: 900, color: '#0f172a', lineHeight: 1.2 }}>{k.value}</span>
                <span style={{ fontSize: 10, fontWeight: 700,
                  color: k.trend === 'up' ? '#16a34a' : '#dc2626' }}>{k.delta}</span>
              </div>
              <div style={{ fontSize: 9, color: '#cbd5e1', marginTop: 1,
                whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                {k.sublabel}
              </div>
            </div>
          ))}
        </div>
      </main>
    </div>
  );
}
